// Name: HASEEB AHMAD
// Department: Electrical Engineering (COM)
// Registration No: BF25NWELE0678
// Section: B
#include <iostream> // tells the compiler to include input output stream library
using namespace std; // tells the compiler to use standard namespace std for each cin and cout

void greet(){      // function declaration 
	
	cout<<" welcome to cpp ";}  // welcome meassage sent to display
	
int main (){  // main function beginns from here
	
	greet();  // function call
	
	return 0;  // tells the computer that program has ended successfully

	
}
	
	

